name: Wholesaler

trigger: [AzurePipelines]

stages:
    - stage: Build
      jobs:
        - job: build
          steps:
            - task: UseDotNet@2
              inputs:
                packageType: 'sdk'
                version: '6.0.x'
            - task: DotNetCoreCLI@2
              inputs:
                command: 'restore'
                projects: '**/*.csproj'
                restoreArguments: '--configuration $(buildConfiguration)'
                feedsToUse: 'select'
            - task: DotNetCoreCLI@2
              inputs:
                command: 'test'
                projects: '**/*Tests.csproj'
            - task: DotNetCoreCLI@2
              inputs:
                command: 'build'
                projects: 'Wholesaler.sln'